import math as m
import numpy as np
import random as rand
import matplotlib.pyplot as plt
from flight.pathfinding.genNodesFromMines import Node, Mine, Field

#purpose: takes in list of nodes outputted from dijkstras algorthm, and creates goto points between each node (arc/line) 
#with hardcoded lengths (arclength/step) between each point, outputting a final path of points for drone to follow.

'''
#make-shift mines for testing. radius = 3 feet
mine1 = Mine(rand.randrange(200), rand.randrange(200), 3)
mine2 = Mine(rand.randrange(200), rand.randrange(200), 3)
mine3 = Mine(rand.randrange(200), rand.randrange(200), 3)
mine4 = Mine(rand.randrange(200), rand.randrange(200), 3)
mine5 = Mine(rand.randrange(200), rand.randrange(200), 3)

n1 = Node(mine1, mine2)
n2 = Node(mine2, mine3)
n3 = Node(mine3, mine4)
n4 = Node(mine4, mine5)

nodeCorList = [n1, n2, n3, n4]
'''
field = Field(0, 200, 0, 200)
field.addMine(100, 150, 10)
field.addMine(60, 90, 10) 
field.addMine(120, 100, 10) 
for mine in field.mines:
    print(mine,'connected to',','.join(m.__str__() for m in mine.connectedMines))

    mine.connectMineNodes()
nodeList = []
for mine in field.mines:
    nodeList.extend(mine.getNodes()) # gives all the nodes generated by adding the mines. 
nodeList

#step for linear, arc_step for arc to determine number of gotopts.
def generateGotoPoints(nodeList:Node, step: int = 10, arc_step: float= 0.349): #arc step in radians for 2 deg
    finalGotoList = []

    for i in range(len(nodeList) - 1):
        n1 = nodeList[i] #first node
        n2 = nodeList[i + 1] #second node in each iteration

        # linear gotos or floating points
        if n1.parentMine!=n2.parentMine or n1.floating or n2.floating:
            x_vals = np.linspace(n1.x, n2.x, step)
            y_vals = np.linspace(n1.y, n2.y, step)

            for x, y in zip(x_vals, y_vals):
                finalGotoList.append((float(x), float(y)))
        
        #arc gotos
        elif n1.parentMine==n2.parentMine:
            #get center coords
            mine = n1.parentMine
            cx, cy = mine.getPos()
            r = mine.getRadius()

            # Compute angles of each node around the circle
            angle1 = n1.angle
            angle2 = n2.angle

            #Choose the smaller arc
            delta_theta = angle2 - angle1

            if delta_theta > m.pi:
                delta_theta -= 2*m.pi
            elif delta_theta < -m.pi:
                delta_theta += 2*m.pi
            
        
            #numPoints = max(5, int(abs(delta_theta) / arc_step)) # 5 is the min num of points --> subject to change.
            numPoints = 5
            # Generate arc points
            angles = np.linspace(angle1, angle1 + delta_theta, numPoints)
            for a in angles:
                x = cx + r * m.cos(a)
                y = cy + r * m.sin(a)
                finalGotoList.append((float(x), float(y)))        
    return finalGotoList

path = generateGotoPoints(nodeList)
print("This is all the points:")
print(path)

print("goto x and goto y")
# Extract x and y from finalGotoList [(x1,y1), (x2,y2)]
goto_x = [coord[0] for coord in path]
goto_y = [coord[1] for coord in path]
print(goto_x)
print('\n'*5)
print(goto_y)


fig, ax = plt.subplots()
ax.set_aspect('equal')

# Plot the goto points in red
plt.plot(goto_x, goto_y, marker='o', color='red', linestyle='-', markersize=4, label='Goto Points')

# Plot the nodes in blue
for node in nodeList:
    plt.plot(node.x, node.y, marker='o', color='blue', markersize= 4, label='Node')

# Add labels and grid
plt.xlabel("X")
plt.ylabel("Y")
plt.title("Nodes and Goto Points")
plt.grid(True)
plt.show()

